export const ADMIN_GETUSERS_FAIL = "ADMIN_GETUSERS_FAIL";
export const ADMIN_GETUSERS_REQUEST = "ADMIN_GETUSERS_REQUEST";
export const ADMIN_GETUSERS_SUCCESS = "ADMIN_GETUSERS_SUCCESS";

export const ADMIN_DELETE_COURSE_FAIL = "ADMIN_DELETE_COURSE_FAIL";
export const ADMIN_DELETE_COURSE_REQUEST = "ADMIN_DELETE_COURSE_REQUEST";
export const ADMIN_DELETE_COURSE_SUCCESS = "ADMIN_DELETE_COURSE_SUCCESS";

export const ADMIN_ADD_COURSE_FAIL = "ADMIN_ADD_COURSE_FAIL";
export const ADMIN_ADD_COURSE_REQUEST = "ADMIN_ADD_COURSE_REQUEST";
export const ADMIN_ADD_COURSE_SUCCESS = "ADMIN_ADD_COURSE_SUCCESS";

export const ADMIN_UPDATE_COURSE_FAIL = "ADMIN_UPDATE_COURSE_FAIL";
export const ADMIN_UPDATE_COURSE_REQUEST = "ADMIN_UPDATE_COURSE_REQUEST";
export const ADMIN_UPDATE_COURSE_SUCCESS = "ADMIN_UPDATE_COURSE_SUCCESS";

export const ADMIN_DELETE_FORUM_FAIL = "ADMIN_DELETE_FORUM_FAIL";
export const ADMIN_DELETE_FORUM_REQUEST = "ADMIN_DELETE_FORUM_REQUEST";
export const ADMIN_DELETE_FORUM_SUCCESS = "ADMIN_DELETE_FORUM_SUCCESS";

export const ADMIN_LOAD_FORUM_FAIL = "ADMIN_LOAD_FORUM_FAIL";
export const ADMIN_LOAD_FORUM_REQUEST = "ADMIN_LOAD_FORUM_REQUEST";
export const ADMIN_LOAD_FORUM_SUCCESS = "ADMIN_LOAD_FORUM_SUCCESS";