export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";

export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";

export const USER_SIGNOUT_FAIL = "USER_SIGNOUT_FAIL";
export const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";

export const USER_CHECKLOGIN_FAIL = "USER_CHECKLOGIN_FAIL";
export const USER_CHECKLOGIN_REQUEST = "USER_CHECKLOGIN_REQUEST";
export const USER_CHECKLOGIN_SUCCESS = "USER_CHECKLOGIN_SUCCESS";

export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_FAIL = "LOAD_COURSES_SUCCESS";

export const LOAD_FORUMS_REQUEST = "LOAD_FORUMS_REQUEST";
export const LOAD_FORUMS_SUCCESS = "LOAD_FORUMS_SUCCESS";
export const LOAD_FORUMS_FAIL = "LOAD_FORUMS_SUCCESS";

export const ADD_FORUM_REQUEST = "ADD_FORUM_REQUEST";
export const ADD_FORUM_SUCCESS = "ADD_FORUM_SUCCESS";
export const ADD_FORUM_FAIL = "ADD_FORUM_SUCCESS";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_SUCCESS";
